### ISSUE TITLE
[Dispensables - Dead code] - (Class : "Rental") 

### ISSUE THREAD

**Issue by hanpaul1004** [Denny-Hwang/AA_23-1_B1_Refactoring#15]
Smell 유형 : [Dispensables - Dead code]

해당클래스 : Rental

내용 : setReturnDate method 미사용

비고: 미사용하는 method는 삭제

**Comment by Denny-Hwang** [comment]
https://github.com/Denny-Hwang/AA_23-1_B1_Refactoring/commit/79c9d71d56c6c94cf584b3711f6eb8790b6961a2
