### ISSUE TITLE
[Dispensables - Duplicate Code] - (Class - "Customer")

### ISSUE THREAD

**Issue by DJHyun** [Denny-Hwang/AA_23-1_B1_Refactoring#5]
- Smell 유형 : [Dispensables - Duplicate Code] 

- 해당클래스 : Customer

- 내용 :  86Line if(totalPoint >= 10), if(totalPoint >= 30) IF절 조건 중복 

- 비고: if(totalPoint >30) 삭제

**Comment by DJHyun** [comment]
![image](https://user-images.githubusercontent.com/28850066/219270485-8aadcd70-24be-4f10-96cc-4523626bbe37.png)

**Comment by Denny-Hwang** [comment]
https://github.com/Denny-Hwang/AA_23-1_B1_Refactoring/commit/b3575454f85310d302f2aaec4c4ee83f2b955049
